### ISSUE TITLE
상단 네비게이션의 스테이터스바 배경색

### ISSUE THREAD

**Issue by devyhan93** [SoFastCar/sofastcar-iOS#54]
텝 네비게이션바의 스테이터스바 부분 배경색이 투명하게 나오는 현상

![image](https://user-images.githubusercontent.com/45344633/92674029-7478ce80-f357-11ea-8529-8b9919144f10.png)

**Comment by tootoomaa** [comment]
이거는 나중에 일괄 수정해야할듯!

main 뷰에서 설정하면 뒤에 모든 뷰 설정 될걸로 예상 ㅋㅋㅋ
변경 하는 방법은 찾아둠
